#端口配置
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
#注册服务器
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5

feign:
  client:
    config:
      default:
        #这里时间一定要调长，否则feign客户端会报ReadTimeOut  服务端报Error parsing HTTP request header
        connect-timeout: 60000
        read-timeout: 60000
        logger-level: basic

spring:
  application:
    name: cops-scada-server
  # 激活哪一个环境的配置文件
  # 因配置文件存放到SVN中，导致无法加载profiles文件会报错
  # 当前移除所有profiles文件，此处配置依然需要保留，因logback和代码中，还存在dev_mac的使用
  profiles:
    active: dev_mac
  #视图配置
  mvc:
    static-path-pattern: /static/**
  #网络请求配置
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  #模板引擎配置
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    settings:
      template_update_delay: 0
      classic_compatible: true
      number_format: 0.######
      template_exception_handler: ignore
    request-context-attribute: rc
    charset: UTF-8
  #redis配置
  redis:
    database: 1
    #host: 192.168.1.244
    host: 192.168.40.39
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接
  #连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.1.244:3306/cops_scada?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    url: jdbc:mysql://192.168.40.39:3306/cops_scada?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: admin
    password: Aa123456
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      reset-stat-enable: true

  #缓存配置
  cache:
    type: redis
    cache-names: cops_scada

  # Mail 相关配置
  mail:
    host: smtp.exmail.qq.com
    username: ermao.wang@lumlux.com
    password: V9gcBRytb8cDXtQ8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  # jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatisPlus
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cops.scada.entity
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: com.cops.scada.entity

  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #    logic-delete-value: 1
    #    logic-not-delete-value: 0
    #自定义填充策略接口实现
    metaObjectHandler: com.cops.scada.config.SysMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#日志
logging:
  config: classpath:log/logback.xml
  path: /home/user/Volumes/Me/path/cops_scada/log

#自定义配置属性
#源码生成文件夹
source-code-dic:  /home/user/Volumes/Me/path/cops_scada/source
source-code-zipfile:  /home/user/Volumes/Me/path/cops_scada/source.zip

#搜索文件生成包的位置
#本地路径
lucence-dic: /home/user/Volumes/Me/path/cops_scada/lucence

#上传文件目录
localUploadPath: /home/user/Volumes/Me/path/cops_scada/file

#上传、下载指定路径
path-resource:
  url: http://127.0.0.1:8081
#  url: http://192.168.1.244:8082

#公共盘信息，主要存放同步每天排产信息
plan-day-disk:
  url: smb://192.168.1.160/个人资料/LLSCR4003/
  domain: lumlux
  username: LLSCR4003
  password: Lumlux123
  filename: HID-生产日计划.xlsx

# Mail模板路径
MailTemplate:
  path: /home/user/Volumes/Me/path/cops_scada/mail_template

# Mail发送
# Mail抄送
MailCC:
  CC: ermao.wang@lumlux.com

# Mail收件人
MailTo:
  To: ermao.wang@lumlux.com,wei.long@lumlux.com,tieqi.xiao@lumlux.com

# 临时目录
appDataTemp:
  path: /home/user/Volumes/Me/path/cops_scada/app_data_temp

---
#开发环境配置
spring:
  profiles: elementary