spring:
  application:
    name: cops-eureka-server
  profiles:
    active: eureka-base
---
server:
  port: 8761
spring:
  profiles: eureka-base
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
server:
  port: 8759
spring:
  profiles: docker-eureka1
eureka:
  instance:
    hostname: docker-eureka1        #Eureka实例的主机名
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://docker-eureka2:8760/eureka/,http://docker-eureka3:8761/eureka/  #Eureka节点相互注册
      register-with-eureka: true
---
server:
  port: 8760
spring:
  profiles: docker-eureka2
eureka:
  instance:
    hostname: docker-eureka2        #Eureka实例的主机名
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://docker-eureka1:8759/eureka/,http://docker-eureka3:8761/eureka/  #Eureka节点相互注册
      register-with-eureka: true
---
server:
  port: 8761
spring:
  profiles: docker-eureka3
eureka:
  instance:
    hostname: docker-eureka3        #Eureka实例的主机名
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://docker-eureka1:8759/eureka/,http://docker-eureka2:8760/eureka/  #Eureka节点相互注册
      register-with-eureka: true
---
server:
  port: 8761
spring:
  profiles: win-bat
eureka:
  instance:
    hostname: localhost        #Eureka实例的主机名
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #Eureka节点相互注册
      register-with-eureka: true