spring:
  profiles:
    active: subversion,config-base
  cloud:
    config:
      server:
        svn:
          uri: https://192.168.1.243/svn/cops/source/cops-cloud-package/cops-configs/
          username: wanglm
          password: 123456
        default-label: trunk
  application:
    name: cops-config-server
---
server:
  port: 8762
spring:
  profiles: config-base
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
---
server:
  port: 8762
spring:
  profiles: docker-config
eureka:
  client:
    healthcheck:
      enabled: true            # 开启健康检查（需要spring-boot-starter-actuator依赖）
    serviceUrl:
      defaultZone: http://docker-eureka1:8759/eureka/,http://docker-eureka2:8760/eureka/,http://docker-eureka3:8761/eureka/
  instance:
    prefer-ip-address: true                   # 开启健康检查（需要spring-boot-starter-actuator依赖）
    lease-expiration-duration-in-seconds: 90  #续约到期时间(单位 S)默认是90S
    lease-renewal-interval-in-seconds: 30     # 续约更新时间间隔（默认30秒）
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: ABC      # eureka可以理解的元数据
      lilizhou: BBC  # 不会影响客户端行为
---
server:
  port: 8762
spring:
  profiles: win-bat
eureka:
  client:
    healthcheck:
      enabled: true            # 开启健康检查（需要spring-boot-starter-actuator依赖）
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true                   # 开启健康检查（需要spring-boot-starter-actuator依赖）
    lease-expiration-duration-in-seconds: 90  #续约到期时间(单位 S)默认是90S
    lease-renewal-interval-in-seconds: 30     # 续约更新时间间隔（默认30秒）
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: ABC      # eureka可以理解的元数据
      lilizhou: BBC  # 不会影响客户端行为